### ISSUE TITLE
Laravel 8 Issues and RuntimeException after running composer require

### ISSUE THREAD

**Issue by Luke-Arch** [area17/twill-api#2]
When initially setting up the module I get the following error when using composer require:
```
Problem 1
    - Root composer.json requires area17/twill-api dev-develop -> satisfiable by area17/twill-api[dev-develop].
    - area17/twill-api dev-develop requires illuminate/support ^9.12 -> found illuminate/support[v9.12.0, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require area17/twill-api:*" to figure out if any version is installable, or "composer require area17/twill-api:^2.1" if you know which you need.
```

Re-running composer require using `composer require area17/twill-api:*` as suggested by the error message, installs the module correctly. with these versions:
```
- Locking area17/twill-api (dev-main 0166f5a)
  - Locking laravel-json-api/core (v2.3.0)
  - Locking laravel-json-api/eloquent (v2.1.1)
  - Locking laravel-json-api/encoder-neomerx (v2.0.1)
  - Locking laravel-json-api/exceptions (v1.1.1)
  - Locking laravel-json-api/laravel (v2.4.0)
  - Locking laravel-json-api/neomerx-json-api (v5.0.1)
  - Locking laravel-json-api/spec (v1.2.0)
  - Locking laravel-json-api/validation (v2.1.0)
```

However yields the following error when artisan attempts to auto-discover these packages after the composer require call:

```
  RuntimeException 

  Server v1 does not exist in config or is not a valid class.

  at vendor/laravel-json-api/core/src/Core/Server/ServerRepository.php:69
     65▕ 
     66▕         $class = $this->config()->get("jsonapi.servers.{$name}");
     67▕ 
     68▕         if (empty($class) || !class_exists($class)) {
  ➜  69▕             throw new RuntimeException("Server {$name} does not exist in config or is not a valid class.");
     70▕         }
     71▕ 
     72▕         try {
     73▕             $server = new $class($this->app, $name);

      +12 vendor frames 
  13  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()

      +5 vendor frames 
  19  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

From my investigations of both the documentation available here and laravel-json-api, there's no clear-cut way to get this module up and running that I can find.

I'm currently running Laravel v8.83.25 with a fresh install of Twill, with no other additions/features/functionality

**Comment by rzauls** [comment]
Im having the same issue with a fresh laravel project, freshly added twill base package and cannot progress from this point onwards.

**Comment by ptrckvzn** [comment]
Hello @Luke-Arch, sorry for the long delay before looking into that. I will comment for other people who might end up here.

`twill-api` depends on Laravel JSON:API package and so, the minimum Laravel version supported would be [Laravel - ^8.76 or ^9.0](https://laraveljsonapi.io/docs/2.0/getting-started/#installation-2) according to their documentation.

Regarding the other error about the server v1 that does not exist, I updated the documentation and installation process (along making it much simpler than early dev version). If you update you package to the current develop branch and follow the instruction, you should not run into this issue.

I am closing this for now, but please re-open if you run into this issue again.
